export type Lang = "lt" | "en" | "ru";

export const searchCopy = {
  lt: {
    back: "Grįžti į pradžią",
    heading: "Raskite savo automobilį",
    sub: "Peržiūrėkite automobilius ir užbaikite užsakymą",
    pickupLocation: "Paėmimo vieta",
    pickupLabel: "Paėmimas",
    returnLabel: "Grąžinimas",
    editSearch: "Keisti paiešką",
    apply: "Taikyti",
    modeOffice: "Carbonus ofisas",
    modeDruskininkai: "Druskininkai",
    modeOther: "Kitas miestas",
    officeSummary: "Paėmimas Carbonus ofise",
    druskininkaiSummary: "Pristatymas Druskininkuose",
    otherSummary: "Pristatymas į pasirinktą vietą",
    officeTitle: "Paėmimas ir grąžinimas Carbonus ofise",
    officeAddress: "M. K. Čiurlionio g. 51, Druskininkai",
    free: "Nemokamai",
    deliveryHeading: "Kur pristatyti automobilį?",
    deliverySubDruskininkai:
      "Druskininkuose automobilį pristatysime nemokamai į jūsų pasirinktą viešbutį ar kitą adresą.",
    deliverySubOther:
      "Pasirinkite viešbutį, miestą ar adresą – iškart parodysime pristatymo ir atsiėmimo kainą.",
    deliveryLocation: "Pristatymo vieta",
    placeholderDruskininkai: "Viešbutis, gatvė arba adresas",
    placeholderOther: "Viešbutis, miestas arba adresas",
    freeDelivery: "Nemokamas pristatymas",
    chooseLocationError: "Pasirinkite pristatymo vietą",
    noResults: "Rezultatų nerasta",
    clear: "Išvalyti",
    returnHeading: "Kur grąžinsite automobilį?",
    returnSame: "Ta pati vieta",
    returnSameDesc: "Automobilį paimsime iš tos pačios vietos",
    returnOffice: "Carbonus ofisas",
    returnOfficeDesc: "M. K. Čiurlionio g. 51, Druskininkai",
    returnOther: "Kita vieta",
    returnOtherDesc: "Pasirinkite kitą adresą atsiėmimui",
    collectionLocation: "Atsiėmimo vieta",
    mapHint: "Patikslinti vietą žemėlapyje",
    mapUnavailable: "Žemėlapis šiuo metu nepasiekiamas.",
    markerOffice: "Carbonus ofisas",
    markerDelivery: "Pristatymo vieta",
    markerCollection: "Atsiėmimo vieta",
    logisticsDelivery: "Pristatymas",
    logisticsCollection: "Atsiėmimas",
    logisticsTotal: "Logistika iš viso",
    freeUpper: "NEMOKAMAI",
    quote: "Kaina derinama",
    quoteNote: "Šios pristatymo vietos kainos automatiškai apskaičiuoti nepavyko. Susisieksime ir patvirtinsime kainą.",
    notSelected: "pasirinkite vietą",
    calculating: "Skaičiuojama pristatymo kaina…",
    carsHeading: "Jums tinkami automobiliai",
    day: "diena",
    days: "dienos",
    daysMany: "dienų",
    filters: "Filtrai",
    sortBy: "Rūšiuoti:",
    sortRecommended: "Rekomenduojami",
    sortPriceAsc: "Kaina: nuo mažiausios",
    sortPriceDesc: "Kaina: nuo didžiausios",
    sortRating: "Įvertinimas",
    carRental: "Automobilio nuoma",
    total: "Iš viso",
    priceFrom: "Kaina nuo",
    from: "nuo",
    perDay: "/ dieną",
    viewCar: "Peržiūrėti automobilį",
    checking: "Tikrinama…",
    showMore: "Rodyti daugiau automobilių",
    warning: "Pasirinkite pristatymo vietą, kad galėtume apskaičiuoti galutinę kainą.",
    noCars: "Šiomis datomis laisvų automobilių neradome",
    noCarsSub: "Pabandykite pakeisti datas arba filtrus.",
    error: "Nepavyko patikrinti automobilių užimtumo",
    errorSub: "Bandykite dar kartą arba susisiekite su mumis.",
    retry: "Bandyti dar kartą",
    trust: [
      { title: "Reikia pagalbos?", desc: "Susisiekite su mumis – padėsime išsirinkti." },
      { title: "Nemokamas pristatymas", desc: "Druskininkuose pristatome ir paimame nemokamai." },
      { title: "Lankstus užsakymas", desc: "Datas ir vietą galite pakeisti susisiekę su mumis." },
    ],
    filtersTransmission: "Transmisija",
    filtersFuel: "Kuro tipas",
    clearFilters: "Išvalyti filtrus",
  },
  en: {
    back: "Back to home",
    heading: "Find your car",
    sub: "Browse the cars and complete your booking",
    pickupLocation: "Pick-up location",
    pickupLabel: "Pick-up",
    returnLabel: "Return",
    editSearch: "Edit search",
    apply: "Apply",
    modeOffice: "Carbonus office",
    modeDruskininkai: "Druskininkai",
    modeOther: "Another city",
    officeSummary: "Pick-up at the Carbonus office",
    druskininkaiSummary: "Delivery in Druskininkai",
    otherSummary: "Delivery to your chosen location",
    officeTitle: "Pick-up and return at the Carbonus office",
    officeAddress: "M. K. Čiurlionio g. 51, Druskininkai",
    free: "Free",
    deliveryHeading: "Where should we deliver the car?",
    deliverySubDruskininkai:
      "In Druskininkai we deliver the car free of charge to your hotel or any other address.",
    deliverySubOther:
      "Pick a hotel, city or address – we will show the delivery and collection price right away.",
    deliveryLocation: "Delivery location",
    placeholderDruskininkai: "Hotel, street or address",
    placeholderOther: "Hotel, city or address",
    freeDelivery: "Free delivery",
    chooseLocationError: "Please select a delivery location",
    noResults: "No results found",
    clear: "Clear",
    returnHeading: "Where will you return the car?",
    returnSame: "Same location",
    returnSameDesc: "We will collect the car from the same place",
    returnOffice: "Carbonus office",
    returnOfficeDesc: "M. K. Čiurlionio g. 51, Druskininkai",
    returnOther: "Another location",
    returnOtherDesc: "Choose a different address for collection",
    collectionLocation: "Collection location",
    mapHint: "Adjust the location on the map",
    mapUnavailable: "The map is currently unavailable.",
    markerOffice: "Carbonus office",
    markerDelivery: "Delivery location",
    markerCollection: "Collection location",
    logisticsDelivery: "Delivery",
    logisticsCollection: "Collection",
    logisticsTotal: "Logistics total",
    freeUpper: "FREE",
    quote: "Price on request",
    quoteNote: "We could not calculate the price for this location automatically. We will contact you and confirm it.",
    notSelected: "select a location",
    calculating: "Calculating delivery price…",
    carsHeading: "Cars available for you",
    day: "day",
    days: "days",
    daysMany: "days",
    filters: "Filters",
    sortBy: "Sort:",
    sortRecommended: "Recommended",
    sortPriceAsc: "Price: low to high",
    sortPriceDesc: "Price: high to low",
    sortRating: "Rating",
    carRental: "Car rental",
    total: "Total",
    priceFrom: "Price from",
    from: "from",
    perDay: "/ day",
    viewCar: "View car",
    checking: "Checking…",
    showMore: "Show more cars",
    warning: "Select a delivery location so we can calculate the final price.",
    noCars: "No cars available for these dates",
    noCarsSub: "Try changing the dates or filters.",
    error: "Could not check car availability",
    errorSub: "Please try again or contact us.",
    retry: "Try again",
    trust: [
      { title: "Need help?", desc: "Contact us – we will help you choose." },
      { title: "Free delivery", desc: "In Druskininkai we deliver and collect for free." },
      { title: "Flexible booking", desc: "Dates and location can be changed by contacting us." },
    ],
    filtersTransmission: "Transmission",
    filtersFuel: "Fuel type",
    clearFilters: "Clear filters",
  },
  ru: {
    back: "Вернуться на главную",
    heading: "Найдите свой автомобиль",
    sub: "Просмотрите автомобили и завершите заказ",
    pickupLocation: "Место получения",
    pickupLabel: "Получение",
    returnLabel: "Возврат",
    editSearch: "Изменить поиск",
    apply: "Применить",
    modeOffice: "Офис Carbonus",
    modeDruskininkai: "Друскининкай",
    modeOther: "Другой город",
    officeSummary: "Получение в офисе Carbonus",
    druskininkaiSummary: "Доставка по Друскининкай",
    otherSummary: "Доставка в выбранное место",
    officeTitle: "Получение и возврат в офисе Carbonus",
    officeAddress: "M. K. Čiurlionio g. 51, Друскининкай",
    free: "Бесплатно",
    deliveryHeading: "Куда доставить автомобиль?",
    deliverySubDruskininkai:
      "В Друскининкай мы бесплатно доставим автомобиль в ваш отель или по другому адресу.",
    deliverySubOther:
      "Выберите отель, город или адрес – мы сразу покажем стоимость доставки и возврата.",
    deliveryLocation: "Место доставки",
    placeholderDruskininkai: "Отель, улица или адрес",
    placeholderOther: "Отель, город или адрес",
    freeDelivery: "Бесплатная доставка",
    chooseLocationError: "Выберите место доставки",
    noResults: "Ничего не найдено",
    clear: "Очистить",
    returnHeading: "Где вы вернёте автомобиль?",
    returnSame: "То же место",
    returnSameDesc: "Мы заберём автомобиль из того же места",
    returnOffice: "Офис Carbonus",
    returnOfficeDesc: "M. K. Čiurlionio g. 51, Друскининкай",
    returnOther: "Другое место",
    returnOtherDesc: "Выберите другой адрес для возврата",
    collectionLocation: "Место возврата",
    mapHint: "Уточнить место на карте",
    mapUnavailable: "Карта сейчас недоступна.",
    markerOffice: "Офис Carbonus",
    markerDelivery: "Место доставки",
    markerCollection: "Место возврата",
    logisticsDelivery: "Доставка",
    logisticsCollection: "Возврат",
    logisticsTotal: "Логистика всего",
    freeUpper: "БЕСПЛАТНО",
    quote: "Цена по запросу",
    quoteNote: "Не удалось рассчитать цену автоматически. Мы свяжемся с вами и подтвердим стоимость.",
    notSelected: "выберите место",
    calculating: "Рассчитываем стоимость доставки…",
    carsHeading: "Подходящие автомобили",
    day: "сутки",
    days: "суток",
    daysMany: "суток",
    filters: "Фильтры",
    sortBy: "Сортировать:",
    sortRecommended: "Рекомендуемые",
    sortPriceAsc: "Цена: по возрастанию",
    sortPriceDesc: "Цена: по убыванию",
    sortRating: "Оценка",
    carRental: "Аренда автомобиля",
    total: "Итого",
    priceFrom: "Цена от",
    from: "от",
    perDay: "/ сутки",
    viewCar: "Смотреть автомобиль",
    checking: "Проверяем…",
    showMore: "Показать больше автомобилей",
    warning: "Выберите место доставки, чтобы мы рассчитали итоговую цену.",
    noCars: "На эти даты свободных автомобилей нет",
    noCarsSub: "Попробуйте изменить даты или фильтры.",
    error: "Не удалось проверить занятость автомобилей",
    errorSub: "Попробуйте ещё раз или свяжитесь с нами.",
    retry: "Попробовать снова",
    trust: [
      { title: "Нужна помощь?", desc: "Свяжитесь с нами – поможем выбрать." },
      { title: "Бесплатная доставка", desc: "В Друскининкай доставляем и забираем бесплатно." },
      { title: "Гибкий заказ", desc: "Даты и место можно изменить, связавшись с нами." },
    ],
    filtersTransmission: "Коробка передач",
    filtersFuel: "Тип топлива",
    clearFilters: "Очистить фильтры",
  },
} as const;

type DeepMutable<T> = T extends readonly (infer U)[]
  ? DeepMutable<U>[]
  : T extends object
  ? { -readonly [K in keyof T]: DeepMutable<T[K]> }
  : T extends string
  ? string
  : T;

export type SearchCopy = DeepMutable<(typeof searchCopy)["lt"]>;
