// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-cars.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.55.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Connect with your Carbonus account." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-cars.ts
var list_cars_default = defineTool({
  name: "list_cars",
  title: "List fleet cars",
  description: "List Carbonus rental cars with pricing, category and availability flags.",
  inputSchema: {
    only_available: z.boolean().default(false).describe("Return only cars currently marked as available."),
    limit: z.number().int().min(1).max(100).default(50).describe("Maximum number of cars to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_available, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cars").select(
      "id,name,category,year,passengers,fuel,transmission,price_per_day,price_tier1,price_tier2,price_tier3,deposit_amount,is_available,is_premium,license_plate"
    ).order("name").limit(limit);
    if (only_available) query = query.eq("is_available", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cars: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/check-availability.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var dateSchema = z2.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD format").describe("Date in YYYY-MM-DD format (local time).");
var check_availability_default = defineTool2({
  name: "check_availability",
  title: "Check car availability",
  description: "Check whether a specific car is free for a rental period (YYYY-MM-DD dates).",
  inputSchema: {
    car_id: z2.string().trim().min(1).describe("Car id from list_cars."),
    start_date: dateSchema,
    end_date: dateSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ car_id, start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("check_car_availability", {
      p_car_id: car_id,
      p_start_date: start_date,
      p_end_date: end_date
    });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { availability: data }
    };
  }
});

// src/lib/mcp/tools/list-reservations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_reservations_default = defineTool3({
  name: "list_reservations",
  title: "List reservations",
  description: "List Carbonus reservations, optionally filtered by status, car or date range. Access follows the signed-in user's permissions.",
  inputSchema: {
    status: z3.string().trim().nullable().default(null).describe("Filter by reservation status, e.g. confirmed, picked_up, returned."),
    car_id: z3.string().trim().nullable().default(null).describe("Filter by car id."),
    from_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().default(null).describe("Only reservations ending on or after this YYYY-MM-DD date."),
    to_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().default(null).describe("Only reservations starting on or before this YYYY-MM-DD date."),
    limit: z3.number().int().min(1).max(200).default(50).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, car_id, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("reservations").select(
      "id,car_id,car_name,customer_id,start_date,end_date,pickup_time,return_time,rental_days,status,payment_method,total_amount,deposit_amount,created_at"
    ).is("deleted_at", null).order("start_date", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    if (car_id) query = query.eq("car_id", car_id);
    if (from_date) query = query.gte("end_date", from_date);
    if (to_date) query = query.lte("start_date", to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reservations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/fleet-calendar.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var dateSchema2 = z4.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD format");
var fleet_calendar_default = defineTool4({
  name: "fleet_calendar",
  title: "Fleet calendar",
  description: "Return booked and manually blocked date ranges for the whole fleet within a period, to see which cars are free.",
  inputSchema: {
    start_date: dateSchema2.describe("Period start, YYYY-MM-DD."),
    end_date: dateSchema2.describe("Period end, YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const [booked, blocked] = await Promise.all([
      supabase.from("reservation_availability").select("car_id,start_date,end_date").lte("start_date", end_date).gte("end_date", start_date),
      supabase.from("car_blocked_dates").select("car_id,start_date,end_date").lte("start_date", end_date).gte("end_date", start_date)
    ]);
    const error = booked.error ?? blocked.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { booked: booked.data ?? [], blocked: blocked.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yuvugrgoadxbmfvebsiu";
var mcp_default = defineMcp({
  name: "carbonus",
  title: "carbonus",
  version: "0.1.0",
  instructions: "Tools for Carbonus car rental. Use `list_cars` for the fleet and pricing, `check_availability` for a single car and date range, `fleet_calendar` for booked and blocked periods across the fleet, and `list_reservations` for booking records. All dates are YYYY-MM-DD local time.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_cars_default, check_availability_default, fleet_calendar_default, list_reservations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
